version: '3.3'
services:
  payment-bill-api:
    image: repo.sadad.co.ir/repository/baam-docker-registry/payment-bill-api:BUILD_NUMBER
    container_name: payment-bill-api
    hostname: payment-bill-api
    networks:
      neo-baam:
        aliases:
          - payment-bill-api
    ports:
      - 8517:8517
      - 9513:9513
#      - 1697:1616
#      - 9078:8000
    #    volumes:
    #      - /opt/configs/pichak-api:/opt/configs/pichak-api
    tty: true
    extra_hosts:
      - "cache: 192.168.53.58"
    #    - eb.bmi.ir: 192.168.52.93
    volumes:
      - /var/log/payment-bill-api:/var/log/payment-bill-api
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JVM_OPTS=-Dfile.encoding=UTF8
#      - JAVA_OPTS="-Dspring.config.location=/opt/configs/ebp/"
    working_dir: /
    build: .
    restart: always
networks:
  neo-baam:
    driver: bridge
