version: '3.3'
services:
  payment-bill-api:
    image: repo.sadad.co.ir/repository/baam-docker-registry/payment-bill-api:BUILD_NUMBER
    container_name: payment-bill-api
    hostname: payment-bill-api
    networks:
      neo-baam:
        aliases:
          - payment-bill-api
    ports:
      - 8517:8517
      - 9513:9513
    tty: true
    extra_hosts:
      - "psp-payment-gateway-srv : 192.168.53.73"
    volumes:
      - /var/log/payment-bill-api:/var/log/payment-bill-api
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JVM_OPTS=-Dfile.encoding=UTF8
    working_dir: /
#    build: .
#    restart: always
    command: [ "/usr/bin/java", "-jar", "/payment-bill-api-0.0.1-SNAPSHOT.jar" ]
networks:
  neo-baam:
    driver: bridge
