
server:
  port: 8517
  servlet:
    context-path: /api/payment-bill

spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
        format_sql: true
        default_schema: db2inst1
  datasource:
    url: jdbc:db2://192.168.97.134:50000/BMI_API
    username: db2inst1
    password: 123456
    driver-class-name: com.ibm.db2.jcc.DB2Driver

#http://thirdparty:9080/api/v0
#http://185.203.161.9:9016/api/v0
#https://sadad.shaparak.ir/api/v0
sadad:
  psp:
    base-url: http://185.203.161.9:8099/api/v0
    payment:
      init-address: /Request/PaymentRequest
      verify-address: /Advice/Verify
    merchant-id: "000000140331692"
    terminal-id: "24056544"
    return-url: "www.sample.com/returnedPage"
    tripleDesKey: "hFI5UOwh9PUDbItN4k8/AacrnC5nTrk2"

ipg:
  request_token:
    url: http://psp-payment-gateway-srv:9039/psp-payment-gateway/resources/ipg/billRequest
  verify_payment:
    url: http://psp-payment-gateway-srv:9039/psp-payment-gateway/resources/ipg/verify


tripleDesKey: tItCjTOXxbN72CYfwd08e2X/m6/Ny7wx

invoice:
  terminalId: 24095735
  merchantId: 000000140336994
  returnUrl: https://www.sadad.co.ir/returnedPage

#for testing
#invoice:
#  terminalId: 24095674
#  merchantId: 000000140336964
#  returnUrl: https://www.sadad.co.ir/returnedPage

#tripleDesKey: 8v8AEee8YfZX+wwc1TzfShRgH3O9WOho

#  ticketVerificationUrl=http://sso:9080/session-manager/devices/verify
#  tokenServerURL=http://sso:9080/identity/oauth2/auth/token
#  authorizationPrefix=Basic a2V5OnNlY3JldA==
#  scope=device-session-verification

springdoc:
  swagger-ui:
    path: /api.html

###############################__SSO
bmi.oauth2.excluded-urls:
  /invoice/swagger-ui/**:*,
  /swagger-ui/**:*,
  /api/payment-bill/api.html:*,
  /api.html:*,
  /v3/**:*,
  /h2/**:*,
  /swagger-ui.html:*,
  /webjars/**:*,
  /v2/**:*,
  /swagger-resources/**:*,
  /invoice:PUT,
  /invoice/id:GET,
  /invoice/oldRegister:*,
  /invoice/ipg-bill-payment:*,
  /invoice/bill-inquiry:*